### ISSUE TITLE
BUGLE doesn´t start after AoW Chapter 3

### ISSUE THREAD

**Issue by Heptamer** [vstojkovic/bugle#2]
Hi, since the last update from FC Bugle is not starting anymore, the following error occurs:

Dec 16 13:07:58.739 ERRO Error with Conan Exiles installation, error: missing field `name` at line 1 column 2400

**Comment by vstojkovic** [comment]
Hi, sorry for the delay. With the help from several other affected users, I've managed to ascertain that the problem is with the "Tot!" mods. Their `modinfo.json` is a bit wonky -- uses different capitalization for its key names -- so I have to make BUGLE handle that correctly.

I'll be issuing a hotfix soon.

Sorry for the inconvenience.

**Comment by Heptamer** [comment]
Thanks for your reply! I really like your piece of Software and appreciate the time and efforts you are spending. Thanks a lot for this!

**Comment by vstojkovic** [comment]
The new release has been published. Hopefully, it should solve this particular problem for everyone affected.
